### PR TITLE
CI: Add workflow to verify test vectors are up-to-date

### PR DESCRIPTION
**Pull request by str4d**
Also commits all test vectors we can generate.

### CODE REVIEW

**Comment by nuttycom** [comment]
I think that something's missing from this commit; I attempted to reproduce the test vectors and get this: ```
nuttycom@sword:~/work/zcash-test-vectors (ci-check-test-vectors)λ ./regenerate.sh
# f4jumble_long
usage: f4jumble_long.py [-h] [-t {zcash,json,rust}]
f4jumble_long.py: error: argument -t/--target: expected one argument
# f4jumble
usage: f4jumble.py [-h] [-t {zcash,json,rust}]
f4jumble.py: error: argument -t/--target: expected one argument
# orchard_empty_roots
usage: orchard_empty_roots.py [-h] [-t {zcash,json,rust}]
orchard_empty_roots.py: error: argument -t/--target: expected one argument
# orchard_generators
usage: orchard_generators.py [-h] [-t {zcash,json,rust}]
orchard_generators.py: error: argument -t/--target: expected one argument
# orchard_group_hash
usage: orchard_group_hash.py [-h] [-t {zcash,json,rust}]
orchard_group_hash.py: error: argument -t/--target: expected one argument
...
```

**Comment by str4d** [comment]
See the workflow; you need to supply arguments: `./regenerate.sh rust rs` etc. At one point I had the script internalise them and do all three, but it was going to make CI three times slower, so now the CI passes those args.

**Comment by str4d** [comment]
The error in the JSON workflow was expected by me because I'd seen it locally (turns out there's a bug in the `orchard_merkle_tree.py` test vector generator that means it can generate Rust but not JSON), but the CI should continue to check the other two. Fixing...

**Comment by str4d** [comment]
Excellent, CI is detecting the bad JSON serializations, but confirming the Rust test vectors all run fine and match the checked-in data. Opened #64 for fixing the JSON output for that test.

**Review by nuttycom — APPROVED** [review]
ACK. I have verified that the test vectors being committed here are the same as those I was able to generate locally.

**Comment by therealyingtong** [comment]
Do we expect the `Verify there are no changes` workflow to fail for randomly generated test vectors?

**Comment by daira** [comment]
@therealyingtong All "randomly" generated test vectors use a fixed RNG seed, so they are deterministic.

**Comment by str4d** [comment]
Yep. The use of a seeded RNG enables people to generate many more test vectors if they want; we just hard-code a default seed and test vector count that results in reasonable space coverage.

**Pull request merged**
